Allow use in jsdom environments without `window.CSS`
Before accessing `window.CSS`, the code now checks whether it exists. If
it is undefined, the feature-detection path returns `false`, indicating
no support.

This ensures compatibility with jsdom, commonly used in testing
frameworks like Jest. Since jsdom does not implement `window.CSS`,
calling it previously triggered errors such as:

```
VIDEOJS: ERROR: TypeError: Cannot read properties of undefined (reading 'supports')
```

For more context, see the upstream issue: https://github.com/jsdom/jsdom/issues/3991